apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayf-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kayf-api
  template:
    metadata:
      labels:
        app: kayf-api
    spec:
      containers:
        - name: kayf-api
          image: kayf-api:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kayf-api-service
spec:
  selector:
    app: kayf-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
